version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: sarjdev_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  mysql:
    image: mysql:8.0
    container_name: sarjdev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sarjdev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  esdata:
    driver: local
  mysql_data: